#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

#npm test

#This setting applies formatting to all files in the project.
#npm run format &&  ng lint --fix  && git add .

#This setting formats only the modified files.
npx pretty-quick --pattern "src/**/*.*(ts|json|html|scss)" --staged  && ng lint --fix